### ISSUE TITLE
Can`t build paginator when number of pages is 1

### ISSUE THREAD

**Issue by Vovcharaa** [WieFel/number_paginator#10]
════════ Exception caught by widgets library ═══════════════════════════════════
The following ArgumentError was thrown building LayoutBuilder:
Invalid argument: 1

```
NumberPaginator(
    numberPages: 1,
),
```

flutter 3.3.3 (web)
number_paginator: ^0.2.1
os: MacOS 12.6

**Comment by WieFel** [comment]
Thanks for reporting. Will try to reproduce and get back to you ASAP

**Comment by mziadd** [comment]
Yeah i am having the same issue

**Comment by WieFel** [comment]
@Vovcharaa @mohammedX6 solved and published to version 0.2.2 ;)
