### ISSUE TITLE
Auto size text for arrow buttons

### ISSUE THREAD

**Issue by theFreeman96** [WieFel/number_paginator#14]
The default buttons size is too big for my phone in portrait mode (OnePlus 8T 1080x2400, but I think the viewport is 360x800) because the dots showing when navigating through pages make the numbers disappear.

Missing current page indicator when in page 2:
![Missing current page indicator](https://user-images.githubusercontent.com/90036768/208110780-98c48605-a2a2-4013-ab4f-800350cd985c.jpg)

Because of this issue I set the height of the buttons to 40, in order to make more room for the buttons and the dots, and I noticed that the text inside the buttons scales perfectly but not the arrows.

Arrows are not scaling:
![Arrows are not scaling](https://user-images.githubusercontent.com/90036768/208111521-98e3852f-35eb-45ea-9e50-51cf4641f674.jpg)

Is it possibile to fix this?
Thanks!

**Comment by WieFel** [comment]
<img width="343" alt="image" src="https://user-images.githubusercontent.com/8345062/208487708-1fe14d19-836e-4016-bd12-d4e853c841d9.png">
I now improved the scaling of the arrows and also of the 3 dots. So now hopefully it works well for you. If not, feel free to reopen this ;)


Edit: published in version `0.2.3`
