### ISSUE TITLE
Add Text to the icons

### ISSUE THREAD

**Issue by anekphong** [WieFel/number_paginator#17]
Please add text to the icons on the next and previous pages. 
For example: < Prev 1  2  3  4  5  6  7  8  9  10 Next >

**Comment by WieFel** [comment]
@anekphong ok, i will create a possibility to add that

**Comment by WieFel** [comment]
@anekphong sorry for the delay.

Finally, the new version `0.4.0` is online on pub.dev, with various customisation options.
You can use `prevButtonBuilder` and `nextButtonBuilder` to completely customise the appearance of the buttons. Be aware that you will need to pass a `controller` to the `NumberPaginator` and use the controller in the prev/next button builders, to "manually" implement the prev/next behavior in this case.

Check out [the readme](https://github.com/WieFel/number_paginator#visibilitycustomisation-of-prevnext-buttons) for an example.
