### ISSUE TITLE
Remove arrows option

### ISSUE THREAD

**Issue by mfathy70** [WieFel/number_paginator#18]
Hello, 
Can you please add a possibility to remove the next and previous arrows ? 
or a disabled option like the button disabled option ? 
thank you

**Comment by WieFel** [comment]
@mfathy70 ok, will add it, together with the options in #17

**Comment by WieFel** [comment]
@mfathy70 please check out the new `0.4.0` version's options `showPrevButton` and `showNextButton` which will help you achieve what you want ;)
Also disabled option is now possible by either using custom prev/next button content, or custom prev/next button builder. Check out [the readme](https://github.com/WieFel/number_paginator#visibilitycustomisation-of-prevnext-buttons).
