### ISSUE TITLE
Numbers doesn't switch to highlight the new selected number

### ISSUE THREAD

**Issue by Eweleval** [WieFel/number_paginator#21]
Numbers doesn't switch to highlight the new selected number and the controls doesn't  work accurately 
Hot reload is need to see changes in UI

**Comment by WieFel** [comment]
Hi @Eweleval, I would need a bit more information to understand your problem.
Can you provide a minimal code example that reproduces the problem?

**Comment by ziyadmansy** [comment]
Hello @WieFel ,
He is correct, the pages are not switched at all from the first page.
It is fixed on page 1!

**Comment by WieFel** [comment]
I'm sorry guys but without some code example I can't help you. Can you share a minimal example of your code that reproduces the problem?

**Comment by Eweleval** [comment]
`NumberPaginator(
                        config: NumberPaginatorUIConfig(
                            buttonUnselectedBackgroundColor: secondaryGrey,
                            buttonUnselectedForegroundColor: white,
                            buttonSelectedBackgroundColor: secondaryRed),
                        numberPages: _controller.totalPages.value,
                        onPageChange: (int index) =>
                            _controller.onPageChanged(index),
                      ),`
So I am using GETX hence the observable value, and the onPageChanged is a function in my controller that handles what data is passed

**Comment by WieFel** [comment]
Probably you need to use the `NumberPaginatorController` to control what page should be currently highlighted in the paginator.
Check:
https://github.com/WieFel/number_paginator/tree/main?tab=readme-ov-file#with-controller

Using the controller, you can use the `prev`/`next` methods or the `currentPage` setter to update the currently highlighted page.
