### ISSUE TITLE
How to know current selected, if selected on midle (ex: selected is 5, from total 10) ? 

### ISSUE THREAD

**Issue by gabrielmulyawan** [WieFel/number_paginator#22]
How to know current selected, if selected on midle (ex: selected is 5, from total 10) ? 

if on midle, only show button with ..

**Comment by WieFel** [comment]
You have 2 possibilities:
1. React on events of `onPageChange` and track the current page yourself by storing it in your widget state. Check out the [example](https://github.com/WieFel/number_paginator/blob/main/example/lib/numbers_page.dart).
2. You can use the controller, and get the current page from the controller: [see example here](https://github.com/WieFel/number_paginator?tab=readme-ov-file#with-controller)
