### ISSUE TITLE
skip button to the first page  

### ISSUE THREAD

**Issue by attatk** [WieFel/number_paginator#8]
I think it's needed to have a forward skip and dots like the implemented one, with customization to show either one or both.

Here is an example:

![gg](https://user-images.githubusercontent.com/72627749/190602206-98126386-9fe7-4e08-96a2-2336d6097f68.gif)

**Comment by WieFel** [comment]
Can you share the code of the custom center part?

**Comment by attatk** [comment]
It's actually your code and added the front part to it and corrected the limits of the center part.

**Comment by WieFel** [comment]
Yeah looks nice!
Could you directly create a PR for it? Would be the easiest

**Comment by attatk** [comment]
okay, I will make sure that it works fine and PR it

**Comment by WieFel** [comment]
Solved by #9
